name: rio
version: 0.0.5
author: Alexander Ewetumo <trinoxf@gmail.com>
description: provides a nice wrapper over HttpRequest class
homepage: http://github.com/influx6/rio
dependencies:
  bass: any
  guardedfs: any
  hub: any
