name: rio
version: 0.0.1
author: Alexander Ewetumo <trinoxf@gmail.com>
description: fs components for sparkflow
dependencies:
  hub: any
  bass: any
  guardedfs: any
dependency_overrides:
  guardedfs:
     path: ../guardedfs
  hub:
     path: ../hub
  bass:
     path: ../bass
